# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8319a7a5fcbf82df835d3438457154f90b55f1643c714194f7252000260b748c262734065295d7cabfcaf538924514b22774bb3bf1ab4e48bd1871377c6a4eaa

test:
  secret_key_base: 2811d16984b0f3d37b27669e987b8e2deb2d9fb9941e04ba59709508a77effd02f3be412d262ed0395b19839b6d2ee92f89fd926277fd58884790965a5ba1a83

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
